
version: '3.8'

services:
  pet-health-dashboard:
    build: .
    container_name: pet-health-app
    ports:
      - "80:3000"
    restart: always
    environment:
      - PORT=3000
      - API_KEY=你的谷歌KEY
      - DEEPSEEK_API_KEY=你的DEEPSEEK_KEY
      - QWEN_API_KEY=你的阿里KEY
      - INFLUX_URL=你的INFLUX公网地址
      - INFLUX_TOKEN=你的TOKEN
      - INFLUX_BUCKET=pet_health
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
